apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aperture.fullname" . }}-config
  labels:
    {{- include "aperture.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
